apiVersion: v1
kind: Pod
metadata:
  name: debug-agent
spec:
  hostNetwork: true
  nodeName: k8s-master
  volumes:
    - name: cri-sock
      hostPath:
        path: /var/run/docker.sock
  containers:
    - name: debug-agent-container
      image: 10.211.55.2:10000/debug-agent:v0.0.1
      env:
        - name: ENV_CONTAINER_ID
          value: de582c538892
      securityContext:
        runAsUser: 0 # warning，run as root，insecure
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: cri-sock
      ports:
        - containerPort: 30000
          hostPort: 30000
